# Generated by Django 2.2 on 2020-09-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='add_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
