# Generated by Django 2.2 on 2020-09-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20200903_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='add_datetime',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='mod_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
