# Generated by Django 2.2 on 2020-09-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20200831_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'ordering': ['-is_active', '-is_superuser', '-is_staff', 'username']},
        ),
    ]
