# Generated by Django 2.2.1 on 2020-09-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_auto_20200930_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='подтверждённый пользоватль'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='электронный адрес'),
        ),
    ]
