# Generated by Django 2.2.1 on 2020-09-29 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20200930_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='is_confirmed',
        ),
    ]
